export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const SHOW_HEAD_UP = "SHOW_HEAD_UP";
export const HIDE_HEAD_UP = "HIDE_HEAD_UP";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";

export const DOCUMENTS_COUNT_LOADED = "DOCUMENTS_COUNT_LOADED";
export const DOCUMENTS_LOADED = "DOCUMENTS_LOADED";

export const CART_LAODED = "CART_LAODED";
